/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "key_touch.h"
#include "key_touch_Control.h"
#include "key_touch_Filter.h"
#include "key_touch_Processing.h"
#include "key_touch_Sensing.h"
#include "key_touch_Structure.h"
#include "key_touch_Tuner.h"
#include "key_touch_Configuration.h"
#include "key_touch_SensingCSD_LL.h"
#include "key_touch_RegisterMap.h"
#include "key_touch_SmartSense_LL.h"
#include "Timer_1.h"
#include "time_1ms_ISR.h"
#include "Clock_1.h"
#include "WAKE_UP.h"
#include "WAKE_UP_aliases.h"
#include "SIMPLE_CLOCK.h"
#include "SIMPLE_CLOCK_aliases.h"
#include "SIMPLE_DATA.h"
#include "SIMPLE_DATA_aliases.h"
#include "isr_wdt.h"
#include "key_touch_ISR.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyLFClk.h"

/*[]*/

